name: Deploy to VM

on:
  push:
    branches:
      - master  # или main, как у тебя настроена основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /путь/до/проекта/на/твое_вм
          docker-compose down
          docker-compose up -d
