name: Deploy on Self-Hosted VM

on:
  push:
    branches:
      - master  # Измени на main, если твоя ветка называется main

jobs:
  deploy:
    runs-on: self-hosted  # Работает на ВМ, где установлен runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Stop current containers
        run: docker-compose down

      - name: Rebuild and restart containers
        run: docker-compose up -d --build
